
version: 2.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - checkout
      - run:
          name: App Install
          command: |
            npm run install
      - run:
          name: Back-End Build
          command: |
            npm run build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - "./*"

  test:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Run lint to check errors
          command: |
            npm run check
      - run:
          name: Run test cases
          command: |
            npm run test

  deploy:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - run:
          name: Deploy  App
          command: |
            npm run deploy

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master